eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eurka: true
    fetch-registery: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-83935375.okta.com/oauth2/default
    audience: api://default
